
const SPECIAL_CONSUMABLES = [
    'aloe plant',
    'bat toy',
    'carded cotton',
    'certified acorn',
    'fireweed plant',
    'glass ring',
    'glass wand',
    'goose feather',
    'gum tragacanth',
    'iron ingot',
    'lump of coal',
    'oak gall',
    'oak tree',
    'origami elf',
    'origami flying crane',
    'origami harpsichord',
    'origami mongoose',
    'origami standing crane',
    'pouch of sand',
    'rice paper',
    'ruby shard',
    'set of glass vials',
    'small carnelian',
    'small citrine fragment',
    'small emerald fragment',
    'small lapis lazuli fragment',
    'small malachite fragment',
    'small turquoise',
    'steel bar',
    'steel hilt',
    'stingweed plant',
    'supple leather',
    'tragacanth plant',
    'trollbeard plant',
    'wooden handle',
    'wooden log',
    'wooden pole'
];
